### ISSUE TITLE
Name for snabbwall executable

### ISSUE THREAD

**Issue by takikawa** [aperezdc/snabbswitch#16]
Currently doing `make dist` for snabbwall sets up an executable named `snabbwall` in the resulting tar archive, but that executable prints an error like the following:

```
$ sudo ./snabbwall spy
unsupported program: snabbwall
Usage: ./snabbwall <program> ...
```

Because `snabb` uses the executable name to choose a sub-program. Should we just change the name to `wall` for distribution? (or maybe just `snabb`?)

**Comment by aperezdc** [comment]
It should be `snabb-wall`, IIRC the logic for chosing the first subcommand also checks for the `snabb-` prefix and picks the string after the dash.

**Comment by takikawa** [comment]
Thanks, I made that change.
